// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCakCAmzERqaNyxHrPWIz-IOau4sWS4WZM',
    appId: '1:301557631567:web:f168ed55ebf1cd5cdcb83a',
    messagingSenderId: '301557631567',
    projectId: 'massengerapp-52cd2',
    authDomain: 'massengerapp-52cd2.firebaseapp.com',
    storageBucket: 'massengerapp-52cd2.appspot.com',
    measurementId: 'G-ZVKN7QYY8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADHHe7Ya4S0aEXxaUXl2ZnGFqloRzvkqA',
    appId: '1:301557631567:android:089dcdae9e43ea6fdcb83a',
    messagingSenderId: '301557631567',
    projectId: 'massengerapp-52cd2',
    storageBucket: 'massengerapp-52cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGpEf8jjTKIxjFih7-8HgS7GNdAKn_MA',
    appId: '1:301557631567:ios:c416570f2daab3bddcb83a',
    messagingSenderId: '301557631567',
    projectId: 'massengerapp-52cd2',
    storageBucket: 'massengerapp-52cd2.appspot.com',
    iosBundleId: 'com.example.massenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGpEf8jjTKIxjFih7-8HgS7GNdAKn_MA',
    appId: '1:301557631567:ios:c416570f2daab3bddcb83a',
    messagingSenderId: '301557631567',
    projectId: 'massengerapp-52cd2',
    storageBucket: 'massengerapp-52cd2.appspot.com',
    iosBundleId: 'com.example.massenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCakCAmzERqaNyxHrPWIz-IOau4sWS4WZM',
    appId: '1:301557631567:web:ea5ed8e7d31a23ebdcb83a',
    messagingSenderId: '301557631567',
    projectId: 'massengerapp-52cd2',
    authDomain: 'massengerapp-52cd2.firebaseapp.com',
    storageBucket: 'massengerapp-52cd2.appspot.com',
    measurementId: 'G-W2G83ET2SM',
  );
}
